#!/bin/bash

# 
# Script properties
# 
workingDir=$PWD
scriptPath="$workingDir"/"template-builder"

# 
# script delegation
# 
cat <<EOF >/usr/local/bin/tb
#!/bin/bash

if [ "\$1" = "uninstall" ]; then
    echo "Delete template-builder? [y/n]"
    read shouldDelete

    if [ "\$shouldDelete" != "y" ]; then
        exit 1
    fi
    
    rm -fr $scriptPath
    rm /usr/local/bin/tb
    echo ">> Template-builder uninstalled."

elif [ "\$1" = "update" ]; then
    echo "Update template-builder? [y/n]"
    read shouldUpdate

    if [ "\$shouldUpdate" != "y" ]; then
        exit 1
    fi

    rm -fr $scriptPath
    rm /usr/local/bin/tb
    git clone -b master https://github.com/DeveloperZoneIO/template-builder.git $scriptPath && template-builder/install

    echo ">> Template-builder updated."
elif [ "\$1" = "switch-version" ]; then
    if [ -z "\$2" ]; then
        echo "Please set the version you want to switch to like: tb switch-version 0.2.2"
    fi

    echo "Switch to version \$2? [y/n]"
    read shouldSwitchVersion

    if [ "\$shouldSwitchVersion" != "y" ]; then
        exit 1
    fi

    cd $scriptPath
    git checkout tags/\$2
else
    python $scriptPath \$1 \$2
fi
EOF

chmod +x /usr/local/bin/tb

echo ">> Template builder is now installed!"