#!/bin/bash

# 
# Script properties
# 
workingDir=$PWD
scriptPath="$workingDir"/"template-builder"

# 
# script delegation
# 
cat <<EOF >/usr/local/bin/tb
#!/bin/bash

python $scriptPath \$1 \$2
EOF

chmod +x /usr/local/bin/tb

# 
# script uninstaller
# 
cat <<EOF >/usr/local/bin/uninstall_template_builder
#!/bin/bash

rm -fr $scriptPath
rm /usr/local/bin/tb
rm /usr/local/bin/uninstall_template_builder

EOF

chmod +x /usr/local/bin/uninstall_template_builder

echo ">> Template builder is now installed!"